spring:
  datasource:
    url: mysql://root:ofwyPQGiClQcbltgkKwAiiHeputzBBmZ@ballast.proxy.rlwy.net:49304/railway
    username: root
    password: ofwyPQGiClQcbltgkKwAiiHeputzBBmZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080
