server:
  port: ${PORT:8080}

spring:
  datasource:
    url: mysql://root:ofwyPQGiClQcbltgkKwAiiHeputzBBmZ@ballast.proxy.rlwy.net:49304/railway
    username: root
    password: ofwyPQGiClQcbltgkKwAiiHeputzBBmZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
