server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ballast.proxy.rlwy.net:49304/railway
    username: root
    password: ofwyPQGiClQcbltgkKwAiiHeputzBBmZ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
