server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,text/html,text/css,text/javascript,audio/mpeg,audio/ogg

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:sqlite:./data/fishgame.db}
    driver-class-name: org.sqlite.JDBC
    username:
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  web:
    resources:
      static-locations: file:/opt/fishgame/static/,classpath:/static/

youtube:
  api:
    key: ${YOUTUBE_API_KEY:}
